// Type declarations for CSS Modules
// This tells TypeScript that .module.css files export an object
// where each key is a class name (string) and each value is the
// scoped class name string generated by Next.js.
declare module "*.module.css" {
  const classes: { readonly [key: string]: string };
  export default classes;
}
